#!/usr/bin/env bash

function BuildPackage {
  echo "Building package..."
  cd /workspaces/pypi_smhi
  python smhi/setup.py sdist
  echo "Package built!"
}

function UploadPackage {
  echo "Building package..."
  twine upload /workspaces/pypi_smhi/dist/*
  echo "Package built!"
}

function InstallTabNine {
  echo "Enable TabNine autocomplete"
  mkdir -p /root/.config/TabNine
  cp -f .devcontainer/tabnine_config.json /root/.config/TabNine
  echo "Enter cloudkey:"
  read CLOUD_KEY
  sed -i "s/REPLACE_CLOUD_KEY/$CLOUD_KEY/g" /root/.config/TabNine/tabnine_config.json
  echo "TabNine autocomplete done!"
}
